source 'https://rubygems.org'

gem 'activerecord', '4.2.5', require: 'active_record'
gem 'capybara'
gem 'pry'
gem 'rack-test'
gem 'rake'
gem 'require_all'
gem 'rspec'
gem 'shotgun'
gem 'sinatra'
gem 'sinatra-activerecord', require: 'sinatra/activerecord'
gem 'sinatra-twitter-bootstrap', require: 'sinatra/twitter-bootstrap'
gem 'sqlite3', '~>1.3.6'
gem 'thin'
gem 'tux'
